

# =====================================================
# Configuration
# =====================================================

$projectPath = "E:\Repos\STA2022\STA2.Net8"

# Publish output generated by CustomPublish
$publishPath = "E:\STAPublish"

# Release artifacts (ZIPs, release folders)
$releaseRoot = "E:\STAReleases"

# =====================================================
# Read Version From Project File
# =====================================================

$projectFile =
    Get-ChildItem `
        -Path $projectPath `
        -Filter *.vbproj `
        | Select-Object -First 1

if ($null -eq $projectFile)
{
    Write-Host "No VB project file found." -ForegroundColor Red
    exit 1
}

[xml]$projectXml =
    Get-Content $projectFile.FullName

$Version =
    $projectXml.Project.PropertyGroup.Version |
    Select-Object -First 1

if ([string]::IsNullOrWhiteSpace($Version))
{
    Write-Host "Version element not found in project file." -ForegroundColor Red
    exit 1
}
$releaseFolder = Join-Path $releaseRoot "STA2-v$Version"
$zipFile = Join-Path $releaseRoot "STA2-v$Version.zip"


# =====================================================
# Header
# =====================================================

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host " STA2 Release Builder" -ForegroundColor Cyan
Write-Host " Version: $Version" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# =====================================================
# Create Required Folders
# =====================================================

New-Item `
    -ItemType Directory `
    -Path $publishPath `
    -Force | Out-Null

New-Item `
    -ItemType Directory `
    -Path $releaseRoot `
    -Force | Out-Null

# =====================================================
# Clean Old Publish Output
# =====================================================

Write-Host "Cleaning publish folder..."

Remove-Item `
    "$publishPath\*" `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue

# =====================================================
# Publish
# =====================================================

Set-Location $projectPath

Write-Host ""
Write-Host "Publishing application..." -ForegroundColor Yellow
Write-Host ""

dotnet msbuild -t:CustomPublish

if ($LASTEXITCODE -ne 0)
{
    Write-Host ""
    Write-Host "Publish FAILED." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Publish completed successfully." -ForegroundColor Green

# =====================================================
# Verify Publish Output Exists
# =====================================================

if (-not (Test-Path $publishPath))
{
    Write-Host ""
    Write-Host "Publish folder not found:" -ForegroundColor Red
    Write-Host $publishPath
    exit 1
}

# =====================================================
# Remove Existing Release Folder
# =====================================================

if (Test-Path $releaseFolder)
{
    Write-Host ""
    Write-Host "Removing previous release folder..."

    Remove-Item `
        $releaseFolder `
        -Recurse `
        -Force
}

# =====================================================
# Copy Publish Files To Versioned Release Folder
# =====================================================

Write-Host ""
Write-Host "Creating release folder..."

New-Item `
    -ItemType Directory `
    -Path $releaseFolder `
    -Force | Out-Null

Copy-Item `
    "$publishPath\*" `
    $releaseFolder `
    -Recurse `
    -Force

# =====================================================
# Remove Existing ZIP
# =====================================================

if (Test-Path $zipFile)
{
    Remove-Item `
        $zipFile `
        -Force
}

# =====================================================
# Create ZIP
# =====================================================

Write-Host ""
Write-Host "Creating ZIP package..."

Compress-Archive `
    -Path "$releaseFolder\*" `
    -DestinationPath $zipFile `
    -CompressionLevel Optimal

# =====================================================
# Generate Release Notes Template
# =====================================================

$releaseNotesPath =
    Join-Path $releaseRoot "STA2-v$Version-ReleaseNotes.md"

@"
# STA2 v$Version

## Features

-

## Improvements

-

## Bug Fixes

-

## Testing

- Release validation completed

"@ | Set-Content $releaseNotesPath

# =====================================================
# Results
# =====================================================

Write-Host ""
Write-Host "Release Package Created Successfully" -ForegroundColor Green
Write-Host ""

Write-Host "ZIP:"
Write-Host "  $zipFile"
Write-Host ""

Write-Host "Release Folder:"
Write-Host "  $releaseFolder"
Write-Host ""

Write-Host "Release Notes:"
Write-Host "  $releaseNotesPath"
Write-Host ""

# Open release folder automatically
Start-Process $releaseRoot

Write-Host "Done." -ForegroundColor Green