name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Publish Application
        run: dotnet publish -c Release -o publish

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path publish\* `
            -DestinationPath STA2.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: STA2.zip
          generate_release_notes: true